print("Git is awesome!")
print('Enter your first name:')
x = input()
print('Enter your Surname:')
y = input()
print('Enter your mobile no.')
z = input() 
print('Hello, ' + x + " "+ y)
print('Your Mobile No. is ' + z)