print("Git is awesome!")
print('Enter your first name:')
x = input()
print('Enter your Surname:')
y = input()
print('Enter your mobile no.')
z = input() 
print('Enter your post code.')
postcode = input() 
### Input City
print('Enter your City.')
City = input() 
### Input Address 
print('Enter your Address.')
Address = input() 

print('Hello, ' + x + " "+ y)
print('Your Mobile No. is ' + z)
print('Your Post Code is ' + postcode)
print('You are living at ' + Address + " "+ City )
